# Site settings
title:
name: Harry Donovan
email: harry.bd11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: eachabyss
github_username: HDonovan96

# Build settings
markdown: kramdown
